// Code generated by "stringer -type=FnCode,ExCode -output strings.go"; DO NOT EDIT

package modbus

import "fmt"

const (
	_FnCode_name_0 = "RdCoilsRdInputsRdHoldingRegsRdInputRegsWrCoilWrRegRdExcStatusDiag"
	_FnCode_name_1 = "GetComCntGetComLog"
	_FnCode_name_2 = "WrCoilsWrRegsSlaveId"
	_FnCode_name_3 = "RdFileRecWrFileRecMskWrRegRdWrRegsRdFIFO"
	_FnCode_name_4 = "RdDevId"
)

var (
	_FnCode_index_0 = [...]uint8{0, 7, 15, 28, 39, 45, 50, 61, 65}
	_FnCode_index_1 = [...]uint8{0, 9, 18}
	_FnCode_index_2 = [...]uint8{0, 7, 13, 20}
	_FnCode_index_3 = [...]uint8{0, 9, 18, 26, 34, 40}
	_FnCode_index_4 = [...]uint8{0, 7}
)

func (i FnCode) String() string {
	switch {
	case 1 <= i && i <= 8:
		i -= 1
		return _FnCode_name_0[_FnCode_index_0[i]:_FnCode_index_0[i+1]]
	case 11 <= i && i <= 12:
		i -= 11
		return _FnCode_name_1[_FnCode_index_1[i]:_FnCode_index_1[i+1]]
	case 15 <= i && i <= 17:
		i -= 15
		return _FnCode_name_2[_FnCode_index_2[i]:_FnCode_index_2[i+1]]
	case 20 <= i && i <= 24:
		i -= 20
		return _FnCode_name_3[_FnCode_index_3[i]:_FnCode_index_3[i+1]]
	case i == 43:
		return _FnCode_name_4
	default:
		return fmt.Sprintf("FnCode(%d)", i)
	}
}

const (
	_ExCode_name_0 = "BadFnCodeBadAddressBadValueSrvFailSrvAckSrvBusy"
	_ExCode_name_1 = "ErrParity"
	_ExCode_name_2 = "GwPathNAGwRespFail"
)

var (
	_ExCode_index_0 = [...]uint8{0, 9, 19, 27, 34, 40, 47}
	_ExCode_index_1 = [...]uint8{0, 9}
	_ExCode_index_2 = [...]uint8{0, 8, 18}
)

func (i ExCode) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _ExCode_name_0[_ExCode_index_0[i]:_ExCode_index_0[i+1]]
	case i == 8:
		return _ExCode_name_1
	case 10 <= i && i <= 11:
		i -= 10
		return _ExCode_name_2[_ExCode_index_2[i]:_ExCode_index_2[i+1]]
	default:
		return fmt.Sprintf("ExCode(%d)", i)
	}
}
